title: Smart Harvesting II
baseurl: /smart-harvesting2
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Smart Harvesting II
  #tagline: Header Tagline
  profile_img: #images/avatar.png
  bg: dark
  has_nav: true
  has_social: false
footer:
  content: '&copy; IR-Group, TH Köln. All rights reserved.'
  #links:
  #  - text: Made with Stackbit
  #    url: 'https://www.stackbit.com'
  #    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
#Build
destination: docs
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
