title: Smart Harvesting II
baseurl: /website
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Smart Harvesting II
  #tagline: Header Tagline
  profile_img: #images/avatar.png
  bg: dark
  has_nav: true
  has_social: false
footer:
  content: '&copy; IR-Group, TH Köln. All rights reserved.'
  #links:
  #  - text: Made with Stackbit
  #    url: 'https://www.stackbit.com'
  #    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10

# Conversion
markdown: kramdown #CommonMarkGhPages
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

#Build
destination: docs
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - LICENSE.theme.md
  - README.md
  - README.theme.md
  - getpubs.py
